export {
  default as Icon,
  AccountGroupIcon,
  AccountSchoolIcon,
  AccountTieIcon,
  AlphabetIcon,
  ArrowRightThinIcon,
  BookOpenIcon,
  CalendarStarIcon,
  ChartLineIcon,
  CheckCircleOutlineIcon,
  ChevronUpIcon,
  ChevronRightIcon,
  ClassesIcon,
  ClipboardTextIcon,
  CloseIcon,
  ContactIcon,
  ContactPhonebookIcon,
  EmailIcon,
  HomeIcon,
  LocationLineIcon,
  MapMarkerRadiusIcon,
  MenuIcon,
  PhoneOutlineIcon,
  SchoolIcon,
  ShieldCheckIcon,
  StandardsIcon,
  StudentRegisterIcon,
  SubjectsIcon,
  TeachersIcon,
} from './Icon';
